# Generated by Django 6.0.1 on 2026-01-20 06:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration', models.CharField(help_text='Matrícula ou código do aluno', max_length=20, unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, help_text='Token único para registro de presença via QR Code', unique=True)),
                ('total_presences', models.PositiveIntegerField(default=0, help_text='Total de presenças registradas pelo estudante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['name'],
            },
        ),
    ]
